export type CityPage = {
  slug: string;
  name: string;
  title: string;
  description: string;
  intro: string;
  localPlanning: string;
  apartmentNote: string;
  commercialNote: string;
  nearby: string[];
};

export const cityPages: CityPage[] = [
  { slug: "barrie", name: "Barrie", title: "Movers in Barrie, Ontario | Local & Long-Distance Moving", description: "Looking for reliable movers in Barrie? Surftmove provides apartment, house, office and long-distance moving services in Barrie and across Ontario. Get a quote today.", intro: "Planning a move within Barrie or leaving the city for another Ontario community? Surftmove coordinates household and business moves with a clear quote process, practical scheduling, and careful move-day handling.", localPlanning: "Barrie moves can involve downtown access, suburban driveways, elevators, stairs, or longer travel along the Highway 400 corridor. Share both addresses and access details so the crew and travel time can be planned accurately.", apartmentNote: "For Barrie apartments and condos, confirm elevator booking requirements, loading access, floor number, and parking instructions before move day.", commercialNote: "Barrie businesses can request office moves planned around building access and the equipment, furniture, and files being relocated.", nearby: ["vaughan", "newmarket", "aurora"] },
  { slug: "toronto", name: "Toronto", title: "Toronto Movers | Apartment, Home & Office Moving", description: "Plan a Toronto move with Surftmove. Get help with condos, houses, offices and long-distance moves between Toronto and communities across Ontario.", intro: "Toronto moves require good timing and precise access information. Surftmove helps customers plan condo, house, office, and intercity moves with route details collected before the crew is scheduled.", localPlanning: "Tell us about loading zones, elevators, parking limits, narrow streets, and the best entrance for moving. These details help reduce avoidable delays in a busy city.", apartmentNote: "Condo customers should reserve elevators and confirm move-in or move-out windows with property management before finalizing the schedule.", commercialNote: "For Toronto office moves, identify building access hours, loading dock rules, furniture disassembly needs, and any items requiring special handling.", nearby: ["mississauga", "vaughan", "markham", "pickering"] },
  { slug: "mississauga", name: "Mississauga", title: "Movers in Mississauga | Residential & Office Moving", description: "Surftmove provides house, condo, office and long-distance moving help in Mississauga and across Ontario. Request a clear moving quote online.", intro: "Moving within Mississauga or connecting to another Ontario city? Surftmove plans residential and commercial moves around your addresses, load size, building access, and preferred date.", localPlanning: "Mississauga routes may involve high-rise access, suburban homes, business parks, and busy roads near Toronto Pearson. Accurate pickup and delivery instructions make scheduling more reliable.", apartmentNote: "For apartment and condo moves, share concierge procedures, elevator reservations, floor numbers, and loading-area directions.", commercialNote: "Businesses can request coordinated office relocations with details for loading docks, workstations, equipment, and timing.", nearby: ["toronto", "brampton", "milton", "oakville"] },
  { slug: "brampton", name: "Brampton", title: "Brampton Movers | Local Home & Long-Distance Moving", description: "Need movers in Brampton? Surftmove handles residential, apartment, office and long-distance moves with online quotes and careful planning.", intro: "Surftmove helps Brampton customers move between houses, apartments, offices, and destinations elsewhere in Ontario. We review the route and access requirements before confirming the job.", localPlanning: "Provide driveway, street-parking, stair, elevator, and long-carry details for both locations. Good access information helps match the crew plan to the actual move.", apartmentNote: "Apartment customers should confirm elevator availability, entry instructions, and permitted moving times with their building.", commercialNote: "For business moves, list furniture, technology, files, heavy pieces, and access restrictions that may affect the plan.", nearby: ["mississauga", "vaughan", "milton"] },
  { slug: "vaughan", name: "Vaughan", title: "Movers in Vaughan | House, Condo & Office Moves", description: "Book Vaughan movers for homes, condos, offices and Ontario long-distance routes. Surftmove offers practical planning and online quote requests.", intro: "Whether you are moving within Vaughan or to another part of Ontario, Surftmove can coordinate the crew, travel, and handling around the size and access needs of your move.", localPlanning: "Vaughan moves can range from condo towers to detached homes and commercial spaces. Tell us about elevators, stairs, loading areas, gates, and parking at both addresses.", apartmentNote: "Reserve condo elevators early and provide the building's moving-window and loading instructions with your quote request.", commercialNote: "Office and commercial customers can outline workstations, equipment, loading access, and the preferred downtime window.", nearby: ["toronto", "richmond-hill", "brampton", "aurora"] },
  { slug: "richmond-hill", name: "Richmond Hill", title: "Richmond Hill Movers | Residential & Long-Distance Moves", description: "Surftmove provides residential, condo, office and long-distance moving services in Richmond Hill and across Ontario. Get a quote online.", intro: "Surftmove plans moves in Richmond Hill for households, condo residents, and businesses, including routes to nearby communities and longer destinations across Ontario.", localPlanning: "Share property access, parking, stair, elevator, and oversized-item details. This helps us prepare for both the pickup and destination rather than relying only on load size.", apartmentNote: "For condo moves, check the building's elevator reservation, protective padding, deposit, and loading-area requirements.", commercialNote: "Commercial quote requests should include the number of work areas, equipment, and any restricted access times.", nearby: ["vaughan", "markham", "aurora", "newmarket"] },
  { slug: "markham", name: "Markham", title: "Movers in Markham | Home, Condo & Business Moving", description: "Plan your Markham move with Surftmove. Residential, condo, commercial and long-distance moving quotes are available online.", intro: "From household moves to office relocations, Surftmove helps Markham customers organize the route, crew, access, and handling details before moving day.", localPlanning: "Markham pickup and delivery locations can have different parking and building rules. Include loading access, floor numbers, stairs, and long carries in your request.", apartmentNote: "Condo and apartment customers should arrange elevators and confirm the building's approved moving hours before booking.", commercialNote: "Businesses can describe office furniture, equipment, inventory, and loading access so the quote reflects the real job.", nearby: ["richmond-hill", "toronto", "pickering", "ajax"] },
  { slug: "newmarket", name: "Newmarket", title: "Newmarket Movers | Local & Ontario Moving Services", description: "Surftmove helps with Newmarket house, apartment, office and long-distance moves. Request a moving quote for your Ontario route today.", intro: "Surftmove coordinates Newmarket moves for homes, apartments, and workplaces, including local relocations and longer routes across Ontario.", localPlanning: "Tell us about the load, property type, parking, stairs, elevators, and any heavy pieces at each address. These practical details improve preparation and quote accuracy.", apartmentNote: "Apartment residents should confirm moving hours, elevator access, entrances, and where the truck may load safely.", commercialNote: "Office customers can request a plan based on access hours, furniture, equipment, and the order in which spaces must be moved.", nearby: ["aurora", "richmond-hill", "barrie"] },
  { slug: "aurora", name: "Aurora", title: "Aurora Movers | Residential, Office & Ontario Moves", description: "Get an Aurora moving quote from Surftmove for houses, apartments, offices or long-distance destinations across Ontario.", intro: "Moving in or out of Aurora? Surftmove helps plan residential and business relocations using your actual route, load size, building access, and special-handling needs.", localPlanning: "Driveway access, stairs, long carries, parking, and the number of large items can all affect a move. Add those details when requesting your quote.", apartmentNote: "For multi-unit buildings, confirm elevator booking and entry arrangements at both the pickup and delivery location.", commercialNote: "Aurora businesses can outline furniture, equipment, timing, and site-access requirements for a tailored office-moving quote.", nearby: ["newmarket", "richmond-hill", "vaughan"] },
  { slug: "oshawa", name: "Oshawa", title: "Oshawa Movers | Local & Long-Distance Moving", description: "Surftmove offers residential, apartment, office and long-distance moving support in Oshawa and across Ontario. Start your quote online.", intro: "Surftmove helps Oshawa households and businesses arrange local and intercity moves with clear pickup, destination, load, and access details.", localPlanning: "Whether the move involves a house, apartment, or commercial unit, provide parking, stairs, elevators, long carries, and oversized-item information for both ends.", apartmentNote: "Apartment customers should check permitted moving hours, elevator availability, and loading access before choosing a date.", commercialNote: "For Oshawa office moves, identify business-critical equipment and access windows so the move can be sequenced appropriately.", nearby: ["whitby", "ajax", "pickering"] },
  { slug: "ajax", name: "Ajax", title: "Ajax Movers | Home, Apartment & Office Moving", description: "Request an Ajax moving quote for residential, apartment, office or long-distance service from Surftmove across Ontario.", intro: "Surftmove coordinates Ajax moves for households, tenants, and businesses travelling locally or to another Ontario destination.", localPlanning: "Accurate address and access details help us plan travel, loading, unloading, and the crew required. Include stairs, elevators, parking, and heavy items.", apartmentNote: "If you are moving into or out of an apartment, confirm the elevator schedule and the route from the unit to the truck.", commercialNote: "Commercial clients can provide inventory, workstation, equipment, and site-access details through the custom quote form.", nearby: ["pickering", "whitby", "oshawa", "markham"] },
  { slug: "pickering", name: "Pickering", title: "Pickering Movers | Residential & Ontario Moving", description: "Surftmove handles house, condo, office and long-distance moves in Pickering and throughout Ontario. Get your moving quote online.", intro: "For a move within Pickering or between cities, Surftmove reviews the route, load, property access, and handling needs before confirming the schedule.", localPlanning: "Pickup and delivery conditions may differ, so include parking, elevator, stair, long-carry, and oversized-item details for both addresses.", apartmentNote: "Condo residents should reserve elevator time and confirm loading-zone instructions with building management.", commercialNote: "Businesses can request coordinated relocation support for office furniture, equipment, and files based on their access window.", nearby: ["ajax", "toronto", "markham", "whitby"] },
  { slug: "whitby", name: "Whitby", title: "Whitby Movers | Local, Residential & Office Moves", description: "Plan a Whitby house, apartment, office or long-distance move with Surftmove. Submit your Ontario moving details for a quote.", intro: "Surftmove helps Whitby customers organize residential and commercial moves, from nearby relocations to longer Ontario routes.", localPlanning: "Provide the full route, load size, floors, stairs, elevators, parking, and difficult-access details so the move can be scoped realistically.", apartmentNote: "For apartment or condo moves, share the building's approved time window and elevator or loading arrangements.", commercialNote: "Office-moving requests can include workstation counts, equipment, access times, and the order rooms should be packed or unloaded.", nearby: ["oshawa", "ajax", "pickering"] },
  { slug: "milton", name: "Milton", title: "Milton Movers | House, Apartment & Long-Distance Moving", description: "Get help with a Milton home, apartment, office or long-distance move. Surftmove serves routes across Ontario with online quote requests.", intro: "Surftmove coordinates Milton moves based on the real route, load size, access, and special-handling requirements at pickup and delivery.", localPlanning: "Let us know about narrow access, driveway or street parking, stairs, elevators, and long carries. These factors help shape the crew and timing plan.", apartmentNote: "Apartment and condo residents should confirm the building's elevator, entry, and moving-hour requirements in advance.", commercialNote: "Milton businesses can request office-moving support based on furniture, technology, inventory, and access needs.", nearby: ["mississauga", "oakville", "burlington", "guelph"] },
  { slug: "oakville", name: "Oakville", title: "Oakville Movers | Residential, Condo & Office Moving", description: "Surftmove provides home, condo, office and long-distance moving help in Oakville and across Ontario. Request a quote today.", intro: "Whether you are changing homes within Oakville or moving to another Ontario city, Surftmove helps plan the crew, route, timing, and item handling.", localPlanning: "Describe parking, driveway access, stairs, elevators, long carries, and fragile or heavy pieces at both locations for a more useful quote review.", apartmentNote: "Condo customers should reserve elevators and verify loading arrangements and permitted move times before booking.", commercialNote: "Office moves can be organized around the property's access rules, furniture and equipment list, and preferred operating schedule.", nearby: ["burlington", "mississauga", "milton", "hamilton"] },
  { slug: "burlington", name: "Burlington", title: "Burlington Movers | Home, Office & Ontario Moves", description: "Book moving help in Burlington for houses, apartments, offices and long-distance Ontario routes with Surftmove.", intro: "Surftmove supports Burlington households and businesses with practical planning for local moves and routes to destinations elsewhere in Ontario.", localPlanning: "Each property has different access. Include parking, stairs, elevator arrangements, floor numbers, and difficult or oversized items with your request.", apartmentNote: "For condo and apartment moves, check elevator reservations, building protection rules, and the route to the loading area.", commercialNote: "Businesses can share office access hours, equipment, furniture, and staging priorities for a tailored move plan.", nearby: ["oakville", "hamilton", "milton"] },
  { slug: "hamilton", name: "Hamilton", title: "Hamilton Movers | Local & Long-Distance Moving", description: "Surftmove helps with Hamilton house, apartment, office and long-distance moves across Ontario. Request a clear quote online.", intro: "Surftmove plans Hamilton moves for homes, multi-unit buildings, and workplaces, including local relocations and longer Ontario routes.", localPlanning: "Stairs, property access, parking, long carries, and heavy furniture can affect the move plan. Add those details for pickup and destination when requesting a quote.", apartmentNote: "Apartment customers should confirm elevator access where available and describe stair-only access or limited loading areas clearly.", commercialNote: "Hamilton businesses can request an office move planned around site access, furniture, equipment, and preferred downtime.", nearby: ["burlington", "oakville", "guelph"] },
  { slug: "kitchener", name: "Kitchener", title: "Kitchener Movers | Residential & Office Moving", description: "Plan a Kitchener home, apartment, business or long-distance move with Surftmove. Get an Ontario moving quote online.", intro: "Surftmove coordinates Kitchener moves for households, renters, and businesses, from nearby addresses to longer destinations across Ontario.", localPlanning: "Share parking, entrances, stairs, elevators, floors, and large-item information. The route from the space to the truck matters at both ends of a move.", apartmentNote: "For apartments and condos, confirm move windows, elevator reservations, and loading access with the property manager.", commercialNote: "Office customers can list workstations, files, equipment, and access constraints so the relocation can be sequenced efficiently.", nearby: ["waterloo", "guelph", "hamilton"] },
  { slug: "waterloo", name: "Waterloo", title: "Waterloo Movers | Apartment, Home & Office Moves", description: "Surftmove provides Waterloo residential, apartment, office and long-distance moving services across Ontario. Start a quote online.", intro: "Moving a Waterloo apartment, home, or workplace? Surftmove plans the route and move-day requirements from the details you provide before confirmation.", localPlanning: "Tell us about floors, elevators, stairs, parking, long carries, and furniture assembly. Complete information helps prevent move-day surprises.", apartmentNote: "Tenants and condo residents should verify their building's elevator, loading, and approved moving-time requirements.", commercialNote: "Businesses can request a move plan based on equipment, work areas, site access, and the order needed for setup at the destination.", nearby: ["kitchener", "guelph", "milton"] },
  { slug: "guelph", name: "Guelph", title: "Guelph Movers | Local Home & Ontario Moving", description: "Get a quote for a Guelph house, apartment, office or long-distance move with Surftmove, serving destinations across Ontario.", intro: "Surftmove assists Guelph customers with residential and commercial moves, including local routes and relocations to other Ontario communities.", localPlanning: "Provide access and item details for both properties, including parking, stairs, elevators, long carries, fragile items, and heavy pieces.", apartmentNote: "Apartment customers should arrange entry and elevator access in advance and identify any stair-only sections.", commercialNote: "Guelph office moves can be scoped around furniture, equipment, operating hours, and loading access.", nearby: ["kitchener", "waterloo", "milton", "hamilton"] },
];

export type ServicePage = {
  slug: string;
  name: string;
  title: string;
  description: string;
  intro: string;
  audience: string;
  benefits: string[];
  faqs: { q: string; a: string }[];
};

export const servicePages: ServicePage[] = [
  { slug: "residential-moving", name: "Residential Moving", title: "Residential Moving Services in Ontario", description: "Plan a house or townhouse move with Surftmove. We provide residential moving help for local and long-distance routes across Ontario.", intro: "Residential moves are easier to plan when the quote reflects the home, belongings, access, and route. Surftmove collects those details before confirming your crew and schedule.", audience: "Homeowners, renters, families, and individuals moving between houses or townhomes within Ontario.", benefits: ["Planning based on your route and load size", "Space to identify fragile, heavy, or oversized items", "Local and intercity Ontario options", "Online booking and custom quote requests"], faqs: [{q:"How early should I request a residential move?",a:"Earlier notice gives more time to review access, route, and scheduling. Availability depends on your requested date."},{q:"Can I include heavy or fragile items?",a:"Yes. Add them to the custom quote details so the handling requirements can be reviewed before confirmation."},{q:"Do you move between Ontario cities?",a:"Yes. Submit both addresses to request a quote for an eligible Ontario route."}] },
  { slug: "apartment-condo-moving", name: "Apartment & Condo Moving", title: "Apartment & Condo Movers in Ontario", description: "Surftmove plans apartment and condo moves across Ontario, including elevator, stair, loading and building-access details. Get a quote online.", intro: "Apartment and condo moves often depend on building rules as much as distance. We ask for floors, elevators, stairs, parking, and loading access so the plan matches the property.", audience: "Renters, condo owners, students, and property residents moving into or out of multi-unit buildings.", benefits: ["Elevator and stair details included in planning", "Pickup and delivery access reviewed", "Options for local and longer routes", "Packing and furniture-assembly needs can be added"], faqs: [{q:"Do I need to reserve an elevator?",a:"Many buildings require it. Confirm the rules with property management at both addresses before your move date."},{q:"What if there is no elevator?",a:"Tell us the floor and number of stair flights in the quote request so the work can be reviewed accurately."},{q:"Where should the truck park?",a:"Confirm the approved loading area or closest legal access point with the building and share those instructions."}] },
  { slug: "long-distance-moving", name: "Long-Distance Moving", title: "Long-Distance Movers Across Ontario", description: "Request a long-distance moving quote for routes between Ontario cities. Surftmove plans travel, loading, access and delivery details online.", intro: "A longer move needs careful route, timing, load, and delivery planning. Surftmove reviews the origin, destination, access, and requested date before confirming an Ontario long-distance move.", audience: "Households, renters, and businesses relocating between cities or across longer distances within Ontario.", benefits: ["Route-based quote review", "One booking request for pickup and delivery details", "Residential and commercial move options", "Special-handling and budget notes accepted"], faqs: [{q:"How is a long-distance quote prepared?",a:"It uses the route distance, load size, labour estimate, access, and any extra handling details you provide."},{q:"Can I choose the delivery date?",a:"Submit your preferred date and route. The team will review availability and timing before the move is confirmed."},{q:"Do you serve routes outside Ontario?",a:"The website is focused on Ontario service. Contact the team with the full route so availability can be reviewed without assumptions."}] },
  { slug: "office-moving", name: "Office Moving", title: "Office & Commercial Moving Services in Ontario", description: "Plan an Ontario office or commercial move with Surftmove. Share access, equipment, furniture and timing details for a tailored quote.", intro: "Office moves work best when access, equipment, furniture, and setup priorities are documented in advance. Surftmove uses those details to review the crew and schedule needed.", audience: "Offices, small businesses, organizations, and commercial tenants relocating within or between Ontario communities.", benefits: ["Planning around building access", "Furniture and equipment details included", "Local and intercity route options", "Custom notes for sequencing and handling"], faqs: [{q:"Can the move be planned around business hours?",a:"Include your preferred access and downtime window. Scheduling is confirmed after the request is reviewed."},{q:"Can you move office equipment?",a:"List each item and any handling requirements in the custom quote section so the team can assess it."},{q:"What information should the building provide?",a:"Ask about loading docks, elevators, approved moving hours, parking, security access, and protection requirements."}] },
  { slug: "packing-services", name: "Packing Services", title: "Packing Services for Ontario Moves", description: "Add packing help to your Ontario move with Surftmove. Request assistance for boxes, wrapping, preparation and furniture assembly needs.", intro: "Packing support can reduce move-day pressure and help organize items for transport. Tell us what needs packing, wrapping, disassembly, or assembly when requesting your quote.", audience: "Customers who need full or partial packing help, support with fragile items, or furniture preparation for a move.", benefits: ["Full or partial packing needs can be described", "Fragile-item counts included in quote review", "Assembly and disassembly needs can be added", "Packing support coordinated with the moving route"], faqs: [{q:"Can I request packing for only some rooms?",a:"Yes. Describe the rooms or items that need help in your quote notes."},{q:"Should I identify fragile items separately?",a:"Yes. Provide the count and description so suitable handling can be reviewed."},{q:"Are packing materials included?",a:"Packing needs and materials should be confirmed as part of the quote. Use the booking notes to explain what you require."}] },
];

export const cityBySlug = new Map(cityPages.map((city) => [city.slug, city]));
export const serviceBySlug = new Map(servicePages.map((service) => [service.slug, service]));
